application: sekai-in-the-box
version: 1
runtime: php
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: com/img/favicon.ico

- url: /css
  static_dir: com/css

- url: /js
  static_dir: com/js

- url: /img
  static_dir: com/img

- url: /inc/(.*)
  static_files: com/inc/\1
  upload: com/inc/(.*)
  
- url: /.*
  script: com/index.php
