application: sekai-in-the-box
version: 1
runtime: php
api_version: 1

handlers:
- url: /css
  static_dir: com/css

- url: /js
  static_dir: com/js

- url: /img
  static_dir: com/img

- url: /(inc.*)
  static_files: com/\1
  upload: com/(.*)
  
- url: /.*
  static_files: com/index.html
  upload: com/index.html

#- url: /.*
#  script: com/php/init.php
