application: sekai-in-the-box
version: __APP_VERSION__
runtime: php
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: com/img/favicon.ico
  expiration: "2d"

- url: /css
  static_dir: com/css

- url: /js
  static_dir: com/js

- url: /img
  static_dir: com/img
  expiration: "2d"

- url: /inc/(.*)
  static_files: com/inc/\1
  upload: com/inc/(.*)

- url: /((iseer|kimono)\.html)
  static_files: com/\1
  upload: com/(.*\.html)
  
- url: /
  script: com/index.php

- url: /.*
  static_files: com/notfound.html
  upload: com/notfound.html
