application: sekai-in-the-box
version: dev
runtime: php
api_version: 1

handlers:
- url: /css
  static_dir: com/css

- url: /js
  static_dir: com/js

- url: /img
  static_dir: com/img

- url: /(inc.*)
  static_files: com/\1
  upload: com/(.*)
  
- url: /.*
  script: index.php

- url: /.*
  static_files: com/index.html
  upload: com/index.html
