<div class="content_title">exhibition [GHOST AND THE SHELL]</div>

<img src="img/exhibition.jpg" width="200px"/>


URL
<a href="http://isee-tomoe.appspot.com/" target="_blank">http://isee-tomoe.appspot.com/</a>


思い
美術展開催に伴う告知サイトを作成しました。
「シンプルなサイトを」という依頼を元にしたミニマルな構成です。
いくつかの工夫を取り入れることで シンプルでありながらもインパクトを持ち、
独特の世界観を表現しています。

　
technical
使用言語：　HTML, JavaScript(JQuery)
稼働環境：　Google App Engine

source
<a href="https://github.com/sekaiya/isee-tomoe" target="_blank">https://github.com/sekaiya/isee-tomoe</a>


