<div class="content_title">IENA</div>

　　<img src="img/iena.jpg" width="200px"/>


URL
<a href="http://iena-korakuen.appspot.com" target="_blank">http://iena-korakuen.appspot.com</a>



思い
近所にあるお気に入りのパン屋のHPを作成しました。
インタビュー時の言葉「私たちはおいしいパンを焼くのが本業」を大切に、
ソーシャル機能や装飾を控えたシンプルなデザインに仕上げました。
フォントカラーは焼きたてのパンをイメージしています。

※作成に当たり許可をとっています。


technical
使用言語：　HTML, JavaScript(JQuery)
稼働環境：　Google App Engine

特徴：
１・高メンテナンス性
２・容易なコンテンツ更新

詳細は下記GitHub README.md を参照ください。


source
https://github.com/sekaiya/iena




