Twitter Bot @iroironashi

　<img src="img/iroironashi.jpg" width="360px"/>

URL
<a href="http://twitter.com/iroironashi" target="_blank">http://twitter.com/iroironashi</a>

思い
煩雑なTwitterタイムラインの中で憩いとなるつぶやきが欲しくなり作成しました。
著作権の切れた現代詩の中から、特に優れたものをランダムで発言します。

発言は1日2回にとどめ、控えめなことも人気の一因でしょうか、
フォロワー数は1000超と人気の高いBotです。

（相互フォロー機能は現在停止しています）

technical
使用言語：　PHP
稼働環境：　Google App Engine
特徴：ossのtwitteroauth.phpの拡張
　⇒curlが使用できないGAE環境でも使用可能に。
　この拡張は現在GitHub上で申請です(※)

source
<a href="https://github.com/sekaiya/iroironashi" target="_blank">https://github.com/sekaiya/iroironashi</a>



※

