<div class="content_title">fushigi-kissa kimono</div>
大学1年～4年にかけて、学園祭に出店した喫茶店です。

「知らない世界もおもしろい」をコンセプトに、
様々なジャンルの本を展示し自由に手にとってもらえる喫茶店を作りました。
手書きの味わい深い蔵書マップをお客様に提供し、
自分が知らないジャンルの本も手にとってもらえるよう配慮しました。

店名の「きもの」は私が普段、着物をきていたことからの命名です。

好評でしたよ！


- 4年間連続 来場者投票1位
- 4大学での出店　；）


作成した蔵書マップ（クリックで拡大します）
<a href="kimono.html" target="_blank" style="text-decoration: none;"><img src="img/kimono1.png" width=25% />　　　<img src="img/kimono2.png" width=25% /></a>


