<div class="content_title">perfect-php</div>

<a href="https://github.com/sekaiya/perfect-php" target="_blank">https://github.com/sekaiya/perfect-php</a>

思い
<a href="https://github.com/sekaiya/perfect-php" target="_blank">パーフェクトPHP</a>に掲載されている
WebアプリフレームワークのUnitTestを作りました。
このコードはGitHub上で公開しており、 
学習時に必要であれば誰でも参照することができます。

この本に載っているフレームワークを実装するにあたり、Unitテストを作成し、
小さな確認を繰り返すことで動きの確認を行い、理解を深めていきました。

公開することで、ほかの人の理解にもつながればと思っています。

スクリプト言語でのWebアプリ開発を好きになるキッカケを作ってくれた本です。
これからも多くの読者を獲得しますように。


technical
使用言語：　PHP

