<div class="content_title">links</div>
<center><img src ="img/logos.png"/></center>
<div class="subtitle">ブログ</div>主に学習記録です
<a href="http://sekai.hateblo.jp/" target="_blank">http://sekai.hateblo.jp/</a>


<div class="subtitle">GitHub</div>作成したコードを載せています。
<a href="https://github.com/sekaiya" target="_blank">https://github.com/sekaiya</a>


<div class="subtitle">FaceBook</div><a href="https://www.facebook.com/sekai.kobayashi" target="_blank">https://www.facebook.com/sekai.kobayashi</a>


